services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    labels:
      com.github.nginx-proxy.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      # - ./custom_nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - votacion-net

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: agevega@agevega.com
      NGINX_PROXY_CONTAINER: nginx-proxy
    networks:
      - votacion-net

  backend:
    build:
      context: ./src/backend/votacion
    container_name: backend
    restart: on-failure
    expose:
      - "3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./src/backend/votacion:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - votacion-net

  frontend:
    build:
      context: ./src/frontend/votacion
    container_name: frontend
    restart: on-failure
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: gatos-vs-perros.agevega.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: gatos-vs-perros.agevega.com
      LETSENCRYPT_EMAIL: agevega@agevega.com
    volumes:
      - certs:/etc/nginx/certs:ro
      - ./src/frontend/votacion/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - votacion-net

volumes:
  certs:
  vhost:
  html:
  acme:

networks:
  votacion-net:
    driver: bridge
