version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - votacion-net

  backend:
    build:
      context: ./src/backend/votacion
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/backend/votacion:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - votacion-net
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./src/frontend/voto_frontend
    depends_on:
      - nginx
    networks:
      - votacion-net
    ports:
      - "8080:80"

networks:
  votacion-net:
    driver: bridge
