services:

  backend:
    build:
      context: ./src/backend/votacion
    container_name: backend
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/backend/votacion:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - votacion-net

  frontend:
    build:
      context: ./src/frontend/votacion
    container_name: frontend
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      VIRTUAL_HOST: gatos-vs-perros.agevega.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: gatos-vs-perros.agevega.com
      LETSENCRYPT_EMAIL: agevega@agevega.com
    volumes:
      - web-root:/usr/share/nginx/html
      - ./src/frontend/votacion/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - votacion-net

volumes:
  certs:
  vhostd:
  web-root:

networks:
  votacion-net:
    driver: bridge
