# docker-compose.yml
version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend  # Nginx debe esperar que el backend esté disponible, ya que lo usa como proxy.
      - frontend # También puede depender del frontend si Nginx sirve archivos estáticos del mismo.
    networks:
      - votacion-net

  backend:
    build:
      context: ./src/backend/votacion
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/backend/votacion:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - votacion-net
    ports:
      - "3000:3000"
    restart: on-failure  # Reinicia el servicio en caso de fallo.

  frontend:
    build:
      context: ./src/frontend/voto_frontend
    networks:
      - votacion-net
    ports:
      - "8080:80"
    restart: on-failure  # Reinicia el servicio en caso de fallo.

networks:
  votacion-net:
    driver: bridge
