version: '3.8'
services:
  votacion:
    build:
      context: ./src/backend/votacion
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/backend/votacion:/usr/src/app
      - /usr/src/app/node_modules
      - ./certs/global-bundle.pem:/usr/src/app/certs/global-bundle.pem

  voto_frontend:
    build:
      context: ./src/frontend/voto_frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
    depends_on:
      - votacion
