services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    labels:
      com.github.nginx-proxy.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - proxy

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: agevega@agevega.com
      NGINX_PROXY_CONTAINER: nginx-proxy
    networks:
      - proxy

  backend:
    build:
      context: ./src/backend/votacion
    container_name: backend
    restart: unless-stopped
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./src/backend/votacion:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - proxy

  frontend:
    build:
      context: ./src/frontend/votacion
    container_name: frontend
    restart: always
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: gatos-vs-perros.agevega.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: gatos-vs-perros.agevega.com
      LETSENCRYPT_EMAIL: agevega@agevega.com
    volumes:
      - ./src/frontend/votacion/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - proxy

volumes:
  certs:
  vhost:
  html:
  acme:

networks:
  proxy:
    driver: bridge
